steps:
  - id: "Build and push image"
    name: "gcr.io/cloud-builders/docker"
    # Build the image from the web/ context using the web/Dockerfile and pass build-args
    args:
      - build
      - -t
      - "gcr.io/$PROJECT_ID/web-app:$SHORT_SHA"
      - -f
      - web/Dockerfile
      - web
      - --build-arg
      - "NEXT_PUBLIC_FIREBASE_API_KEY=$_NEXT_PUBLIC_FIREBASE_API_KEY"
      - --build-arg
      - "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN"
      - --build-arg
      - "NEXT_PUBLIC_FIREBASE_PROJECT_ID=$_NEXT_PUBLIC_FIREBASE_PROJECT_ID"
      - --build-arg
      - "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET"
      - --build-arg
      - "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID"
      - --build-arg
      - "NEXT_PUBLIC_FIREBASE_APP_ID=$_NEXT_PUBLIC_FIREBASE_APP_ID"
      - --build-arg
      - "NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=$_NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID"
      - --build-arg
      - "NEXT_PUBLIC_API_BASE_URL=$_NEXT_PUBLIC_API_BASE_URL"
    secretEnv:
      - _NEXT_PUBLIC_FIREBASE_API_KEY
      - _NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
      - _NEXT_PUBLIC_FIREBASE_PROJECT_ID
      - _NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
      - _NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
      - _NEXT_PUBLIC_FIREBASE_APP_ID
      - _NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
      - _NEXT_PUBLIC_API_BASE_URL

  - id: "Push image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/web-app:$SHORT_SHA"]

# Optional: publish built image as an artifact
images:
  - "gcr.io/$PROJECT_ID/web-app:$SHORT_SHA"

# Map local secret env names to Secret Manager resources.
# Replace PROJECT_ID in the resource paths below with your GCP project id.
secrets:
  - secretEnv:
      _NEXT_PUBLIC_FIREBASE_API_KEY: "projects/orbit-ai-472708/secrets/NEXT_PUBLIC_FIREBASE_API_KEY/versions/latest"
      _NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: "projects/orbit-ai-472708/secrets/NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN/versions/latest"
      _NEXT_PUBLIC_FIREBASE_PROJECT_ID: "projects/orbit-ai-472708/secrets/NEXT_PUBLIC_FIREBASE_PROJECT_ID/versions/latest"
      _NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: "projects/orbit-ai-472708/secrets/NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET/versions/latest"
      _NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: "projects/orbit-ai-472708/secrets/NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID/versions/latest"
      _NEXT_PUBLIC_FIREBASE_APP_ID: "projects/orbit-ai-472708/secrets/NEXT_PUBLIC_FIREBASE_APP_ID/versions/latest"
      _NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: "projects/orbit-ai-472708/secrets/NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID/versions/latest"
      _NEXT_PUBLIC_API_BASE_URL: "projects/orbit-ai-472708/secrets/NEXT_PUBLIC_API_BASE_URL/versions/latest"

options:
  machineType: "E2_HIGHCPU_8"  # optional - speeds up builds

timeout: "1200s"
