import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "../public/index.css";
import { AuthProvider } from "@/lib/firebase/AuthContext";
import { ReactNode } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        {children}
        {/* Expose backend URL globally to browser scripts */}
        <script
          dangerouslySetInnerHTML={{
            __html: `window.API_BASE = "${process.env.NEXT_PUBLIC_API_BASE_URL}";`,
          }}
        />
      </body>
    </html>
  );
}
